### コメント一覧

GET http://localhost:8000/api/posts/1/comments?offset=1

### コメント作成
POST http://localhost:8000/api/posts/1/comments
Content-Type: application/json

{
    "user_id": 101,
    "comment": "For Beautiful Human Life."
}

### コメント削除
DELETE http://localhost:8000/api/posts/1/comments/108
