
### フォロー中ユーザー取得
GET http://localhost:8000/api/users/101/relations/followings?offset=0&limit=20

### フォローワー取得
GET http://localhost:8000/api/users/101/relations/followers?offset=0&limit=20

### フォローする / 外す
PUT http://localhost:8000/api/users/2/relations/followers/1

### リレーションがあるか
GET http://localhost:8000/api/users/3/relations/followers/1
