# ユーザー一覧取得
GET http://localhost:8000/api/users?keyword=&category_id=3&specialty_id=7&offset=0&limit=20&sort=followers_count


###
GET http://localhost:8000/api/users

###

GET http://localhost:8000/api/users?category=1&specialty=2&offset=0



### ユーザー詳細取得
GET http://localhost:8000/api/users/101


### ロードマップ一覧取得（ユーザー特定）
GET http://localhost:8000/api/users/101/posts


### 全ロードマップ一覧取得（ユーザー特定）
GET http://localhost:8000/api/users/101/posts/all

###
GET http://localhost:8000/api/users/1/posts


### ロードマップ一覧取得（ユーザーマーク済）
GET http://localhost:8000/api/users/101/marks


### ユーザー削除
DELETE http://localhost:8000/api/users/60

### 認証メール再送信
POST http://localhost:8000/api/email/resend
Content-Type: application/json

{
    "email": "hogeaaadposkapojkfpas@gmail.com"
}

### ユーザー詳細更新
PUT http://localhost:8000/api/users/118
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYxNzcwMTM0NywiZXhwIjoxNjE3NzE5MzQ3LCJuYmYiOjE2MTc3MDEzNDcsImp0aSI6Im9rSUJrQ2FhZHhoT0RKYnciLCJzdWIiOjExOCwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.rsaVKEvHQvPz9gzyzfINrVKdOe1_6i5NML1ProeuIl8

{
    "id": 118,
    "name": "hoge",
    "email": "hogeaa@gmail.com",
    "icon_url": "/img/userIcon_default.jpg",
    "email_verified_at": "2021-03-13 06:33:55",
    "profile": {
        "id": 1,
        "user_id": 2,
        "category_id": 3,
        "specialty_id": 7,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna",
        "catch_copy": "For Beautiful Human Life!",
        "sns": [
            {
                "profile_id": 1,
                "sns_id": 1,
                "url": "https://twitter.com/tsuneken0512"
            },
            {
                "profile_id": 1,
                "sns_id": 3,
                "url": "https://www.linkedin.com/in/kentsunekawa/"
            },
            {
                "profile_id": 1,
                "sns_id": 4,
                "url": "https://www.instagram.com/kentsunekawa/"
            },
            {
                "profile_id": 1,
                "sns_id": 2,
                "url": "https://www.facebook.com/profile.php?id=100005913679300"
            }
        ]
    }
}

# {
#     "id": 1,
#     "name": "Ken Tsunekawawa",
#     "email": "tsunekawaken@gmail.com",
#     "icon_url": "/img/icon_1.jpg",
#     "profile": {
#         "id": 1,
#         "user_id": 1,
#         "category_id": 3,
#         "specialty_id": 7,
#         "catch_copy": "For Beautiful Human Life!",
#         "description": "Hi I am Ken!"
#     },
#     "sns": [
#         {
#             "id": 1,
#             "profile_id": 1,
#             "sns_id": 1,
#             "url": "https://twitter.com/tsuneken0512"
#         },
#         {
#             "id": 2,
#             "profile_id": 1,
#             "sns_id": 3,
#             "url": "https://www.linkedin.com/in/kentsunekawa/"
#         },
#         {
#             "id": 3,
#             "profile_id": 1,
#             "sns_id": 4,
#             "url": "https://www.instagram.com/kentsunekawa/"
#         },
#         {
#             "id": 4,
#             "profile_id": 1,
#             "sns_id": 2,
#             "url": "https://www.facebook.com/profile.php?id=100005913679300"
#         }
#     ]
# }


### アイコン更新
PUT http://localhost:8000/api/users/1/icon
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYxNzY2Nzc3MiwiZXhwIjoxNjE3Njg1NzcyLCJuYmYiOjE2MTc2Njc3NzIsImp0aSI6ImdVeDRyeGlpaUYwZXlFWHQiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.ERgSK5iJ8Qipm3mcuFHnudjvOjoSRXzEKOJU6MiOb3E

